name: ccc_dart
description: Chromecast Converter implementation using Dart
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.12.1 <3.0.0'

dependencies:
  args: ^2.2.0
  rxdart: ^0.27.1

dev_dependencies:
  pedantic: ^1.8.0
