name: Builds Master

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ dev/dart ]
#  pull_request:
#    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
#  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        architecture: [ x64, arm ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Dart SDK
        uses: dart-lang/setup-dart@v1
        with:
          sdk: 2.12.1
          architecture: ${{ matrix.architecture }}

      - name: Install dependencies
        run: dart pub get

      - name: Compile the project
        run: dart compile exe -o chromecast_converter bin/ccc.dart

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: chromecast_converter
          path: chromecast_converter
